/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import nico5 from "./nico5.glb";
import { useFrame } from "@react-three/fiber";

export function NicoModel(props) {
	const refMesh = useRef();
	useFrame(({ mouse }) => {
		if (refMesh.current) {
			// console.log(mouse);
			refMesh.current.rotation.z = -mouse.x;
			refMesh.current.rotation.x = 1.7 - mouse.y;
		}
	});

	const { nodes, materials } = useGLTF(nico5);
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.head3d003.geometry}
				material={materials["material_0.003"]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.01}
				ref={refMesh}
			/>
		</group>
	);
}

useGLTF.preload(nico5);
